-- AlterTable
ALTER TABLE "despesas" ALTER COLUMN "data" DROP DEFAULT,
ALTER COLUMN "data" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "entradas" ALTER COLUMN "data" DROP DEFAULT,
ALTER COLUMN "data" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "fechamentos" ALTER COLUMN "data" DROP DEFAULT,
ALTER COLUMN "data" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "materiais" ALTER COLUMN "data" DROP DEFAULT,
ALTER COLUMN "data" SET DATA TYPE TEXT;
