import { Router } from "express";
import userRouter from "./userRouter.js";
import obraRouter from "./obrasRouter.js";
import entradaRouter from "./entradaRouter.js";
import materialRouter from "./materialRouter.js";
import fechamentoRouter from "./fechamentoRouter.js";
import despesaRouter from "./despesaRouter.js";
import funcionarioRouter from "./funcionarioRouter.js";
import empreitaRouter from "./empreitaRouter.js";
import pagamentoRouter from "./pagamentoRouter.js";
import testRouter from "./testesRouters.js";

const router = Router();
router.use(testRouter);
router.use(userRouter);
router.use(obraRouter);
router.use(entradaRouter);
router.use(materialRouter);
router.use(fechamentoRouter);
router.use(despesaRouter);
router.use(funcionarioRouter);
router.use(empreitaRouter);
router.use(pagamentoRouter);
export default router;
